### ISSUE TITLE
first review

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/galaxy-social#13]
* [x] `social_media:` (in the config file) -> rename to media?
* [x] Please convert this into requirements.txt file - we want to avoid editing the GitHub workflows as much as possible
* [x] https://github.com/arash77/galaxy-social/blob/main/.github/workflows/publish_content.yml#L19  -> change wording to something like "get a cache of all published files"
* [x] The cache is absolutely needed, but I'm wondering if we should use it in addition to some time-constrained, e.g. only process files that have been touched in merged commits; assume a user added 3 files in one PR, only those 3 files should be processed correctly? Similar if a user add 3 new files, but in addition adds `media: mastodon -> true` to an older 4 file. All 4 files should be processed. The 4th file should only be tooted to Mastodon
  * [x] To be precise, I'm not saying you should do the git magic in your Python code, rather allow your script to take multiple paths to process a file. Your script should also run locally without GitHub. Github Actions will then figure out the files that have been touched and pass them to the script - e.g. with https://github.com/marketplace/actions/get-all-changed-files
* [x] Consider adding a simple "markdown" plugin type --> This is the most simple plugin, maybe for local testing. It simply creates a markdown file with the news entry
  * [x] This markdown post could be posted as a comment to the PR that the user has created -> some kind of preview for the user
* [x] Let's find a better name for the main.py (just thinking and brainstorming)
* [x] I would move the code (plugins + main.py) into its own subfolder, maybe `lib` or something
  * [x] https://github.com/arash77/galaxy-social/tree/main/plugins you can remove the suffic `_client` from all plugins
* [x] The repo needs a LICENSE
* [x] Do you process all files in this folder https://github.com/arash77/galaxy-social/tree/main/posts; e.g. also when I create a subfolder or many nested subfolders ... you could process all files in a commit ending with *.md that has a minimal set of metadata
* [x] Do you test a PR if all metadata is correct? If not we should do that. E.g. you should have a YAML schema file, as here: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/.schema.yaml and then you can lint the YAML with https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/Makefile#L21 - when I say YAML here, I mean the YAML on top of a post
* [x] use fstrings https://github.com/arash77/galaxy-social/blob/main/main.py#L16
* [x] https://github.com/arash77/galaxy-social/blob/main/main.py#L16 does not look like as it would handle errors well, e.g. if something is misconfigured, a module is not available etc ...
* [x] https://github.com/arash77/galaxy-social/blob/main/main.py#L26 you do twice a content.split() ... you can do that only once in the beginning
* [x] Question: do we have a way to know the final URL of the post? The mastodon link etc ..? It would be nice if the GHA could create a comment after the PR was merged with the final links to check for the user.
* [x] PR your changes to https://github.com/bgruening/galaxy-social

**Comment by wm75** [comment]
https://github.com/arash77/galaxy-social/blob/main/plugins/mastodon_client.py#L12 this one's a server-specific setting in Mastodon so it should become part of the plugins.yml file.
