### ISSUE TITLE
Enhance Post Failure Handling

### ISSUE THREAD

**Issue by arash77** [usegalaxy-eu/galaxy-social#43]
@wm75 asks for improvements to enhance failure handling.
Currently, when a social media post fails partially (e.g., some images fail to upload), the entire post might be published incompletely. This can lead to a negative user experience.

**Proposed Improvements:**
* Implement logic to detect partial failures (image upload errors, API errors).
* If a partial failure occurs:
   * Delete the incomplete post from the platform.
   * Two options on how to handle the next step:
     * Create a separate Pull Request (PR) for the failing social media platforms only.
     * Defining custom triggers based on comments, labels, or closed PRs (instead of on merged PRs as they can be redone).

**Discussion Points:**
* Which approach for handling partial failures best suits our workflow (separate PRs or custom triggers)?
* If implementing custom triggers, what specific options would be most beneficial?

**Comment by bgruening** [comment]
I like the new PR approach. It easier to explain and process from a user pov.
