### ISSUE TITLE
Handling old preview comments

### ISSUE THREAD

**Issue by arash77** [usegalaxy-eu/galaxy-social#66]
Should Galaxy Social hide or delete the old preview comments automatically?

**Comment by bgruening** [comment]
Yes! :)

**Comment by arash77** [comment]
It appears that hiding comments through the API is currently not possible (still investigating potential solutions).
When a new comment is received, should we delete all previous comments from the bot or just the old preview comments? Additionally, should error comments be deleted as well?

**Comment by arash77** [comment]
I could find an API to minimize the comments and add the commit to the PR.
Also, I make it just to do this when it is in the preview phase.
